import Vue from 'vue'

// https://youzan.github.io/vant/#/zh-CN/home
import {
    Button,
    Divider,
    Collapse,
    CollapseItem,
    Empty,
    Tab,
    Tabs,
    Row,
    Col,
    Stepper,
    Toast,
    Dialog,
    Popup,
    Field,
    Form,
    Notify,
    Cell,
    CellGroup,
    NavBar,
    Search,
    Image,
    Lazyload,
    Swipe,
    SwipeItem,
    Loading,
    Tag,
    CountDown,
    Tabbar,
    TabbarItem,
    List,
    PullRefresh,
    TreeSelect,
    Icon,
    Progress,
    ImagePreview,
    Rate,
    GoodsAction,
    GoodsActionIcon,
    GoodsActionButton,
    Sku,
    AddressList,
    AddressEdit,
    SwipeCell,
    Card,
    SubmitBar,
    Checkbox,
    CheckboxGroup,
    Grid,
    GridItem,
    DropdownMenu,
    DropdownItem,
    ContactCard,
    ContactList,
    ContactEdit
} from 'vant'

Vue.use(Toast)
    .use(Stepper)
    .use(Col)
    .use(Row)
    .use(CollapseItem)
    .use(Collapse)
    .use(Popup)
    .use(Empty)
    .use(Dialog)
    .use(Notify)
    .use(Divider)
    .use(Field)
    .use(Form)
    .use(Button)
    .use(Cell)
    .use(CellGroup)
    .use(NavBar)
    .use(Search)
    .use(Image)
    .use(Lazyload)
    .use(Swipe)
    .use(SwipeItem)
    .use(Loading)
    .use(Tag)
    .use(CountDown)
    .use(Tabbar)
    .use(Tab)
    .use(Tabs)
    .use(TabbarItem)
    .use(List)
    .use(PullRefresh)
    .use(TreeSelect)
    .use(Icon)
    .use(Progress)
    .use(ImagePreview)
    .use(Rate)
    .use(GoodsAction)
    .use(GoodsActionIcon)
    .use(GoodsActionButton)
    .use(Sku)
    .use(AddressList)
    .use(AddressEdit)
    .use(SwipeCell)
    .use(Card)
    .use(SubmitBar)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Grid)
    .use(GridItem)
    .use(DropdownMenu)
    .use(DropdownItem)
    .use(ContactCard)
    .use(ContactList)
    .use(ContactEdit)
